{
  "comments": [
    {
      "key": {
        "uuid": "520760f3_e7b46636",
        "filename": "resources/libraries/python/LoadBalancerUtil.py",
        "patchSetId": 11
      },
      "lineNbr": 116,
      "author": {
        "id": 1263
      },
      "writtenOn": "2019-09-24T11:15:47Z",
      "side": 1,
      "message": "I believe this is also a VPP error, add to https://gerrit.fd.io/r/c/csit/+/22194\nI will create a VPP fix shortly.",
      "range": {
        "startLine": 116,
        "startChar": 30,
        "endLine": 116,
        "endChar": 35
      },
      "revId": "55ebefe76bf5be582ec9473e01b74f18797c7b9c",
      "serverId": "6d2eb258-4fe2-443e-8a38-ca81da23d4c2",
      "unresolved": true
    }
  ]
}